### ISSUE TITLE
JSON. Мета-задача

### ISSUE THREAD

**Issue by pasaran** [pasaran/yate#131]
По мотивам #62. Синтаксис более-менее вроде понятен. Теперь нужно разбить эту здоровую задачу на мелкие:
- [ ] Задаваемый тип для всех блочных выражений и деклараций: `if`, `for`, `apply`, `match`, `func`. Например,
  
  ```
  array match / { ... }
  ```
  #132
- [x] Грамматика для `object`, `array`, `pair`, `item`. #133 
- [x] Простая генерация объектов и массивов (т.е. без внутренних `apply`). #134 
- [x] Подумать. Тип `item` -- это отдельный тип или модификатор? `item/xml`, `item/scalar`, ...? #135 
- [x] Отдельный тип для всего документа `Doc`, на который можно делать `apply`. Т.е. `root` будет частью этого документа. Так же как и все глобальные переменные и ключи. #136 
- [x] В рантайме унести переменные и ключи из модуля в `Doc`. #137 
- [x] Приведение объектов/массивов к `Doc`. #138 
- [x] `chroot` #129 
- [x] `apply` на объект/массив. #139 
- [x] Передача объекта/массива в качестве параметра в функцию/шаблон #143 
- [ ] Приведение `object` к `attrs`. #140 
- [ ] Нужно разделить матчер на 3 (для `xml`, `object`, `array`). Если не на 5 (еще `pair` и `item`). #141 
- [ ] Генерация JSON'а из yate. #216 

Это более-менее необходимый минимум для этой задачи.
